colors:
  bg: "#303030"
  axes: "white"
  grid: "#C0C0C0"
  green_bar: "#90EE90"
  red_bar: "#FF474C"
  price_line: "#AAAAAA"
  volume_bar: "#4C6EF5"
  mean_line: "#7F8C8D"
  header_text: "#7F8C8D"

design:
  axes_right: True
  figure_padding: 0.05
  lim_buffer:
    x_axis: 2
    y_axis: 2
  grid_line:
    style: "--"
    alpha: 0.2
  last_price:
    style: ":"
    alpha: 0.9
  volume_bar_alpha: 0.8
  volume_mean:
    style: "-"
    alpha: 0.5
  header:
    large_font: 40
    small_font: 20